### PR TITLE
FCREPO-1961: Use Guava utilities for dynamic proxies

### PR DESCRIPTION
**Pull request by ajs6f**

### CODE REVIEW

**Comment by acoburn** [comment]
I'm +1 on this change. Since the PR is targeting `master` we can either wait until after the 4.5.1 release is finalized or you can close this PR and make another one, pointing at the `DEV` branch. Either way is fine by me.

**Comment by awoods** [comment]
The PR seems fine... although our trend seems to have been to move from Guava to standard Java, and this PR is doing the opposite.
In any case, we can either merge with `DEV` sooner, or `master` after the 4.5.1 release.

**Comment by ajs6f** [comment]
No, the trend has been to replace Guava with straight Java 8 bits, when there is an obvious equivalent (the Stream API, `Optional`, etc.).

**Comment by ajs6f** [comment]
I'd just as soon let it sit and merge post-shuffle.

**Comment by awoods** [comment]
@ajs6f, in an effort to clean out the backlog of work (like this) that is ready to go... would you mind re-targeting this PR on `DEV`, and I will move it forward?

**Comment by ajs6f** [comment]
Closed in favor of https://github.com/fcrepo4/fcrepo4/pull/1025

**Pull request closed without merging**
