### PR TITLE
Explicitly encode test objects as utf8

### PR DESCRIPTION
**Pull request by birkland**
Resolves [FCREPO-2370](https://jira.duraspace.org/browse/FCREPO-2370) for 4.7.1-RC

### CODE REVIEW

**Comment by acoburn** [comment]
@birkland, as this only affects test code, am I correct in understanding that this change is _not_ intended to result in a RC-2?

**Comment by birkland** [comment]
@acoburn Right, this only affects test code.  However, it's necessary for Windows testers in order to build the RC in the first place without disabling tests.  So they can build the RC from this PR, or the 4.7.1-RC branch should this PR be merged into it.

**Comment by bseeger** [comment]
@birkland - would you mind running a build with the 4.7.1 RC candidate code adding this to your java opts:

`-Dfile.encoding=UTF-8`

And seeing if the tests pass then?  

Thanks!

**Comment by birkland** [comment]
After a little bit of trial and error, this seemed to do the trick:
    
    export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"

It seems like a plausible workaround for evaluating 4.7.1-RC without changes to any files

**Pull request merged**
