### PR TITLE
remove redundant javadoc commands

### PR DESCRIPTION
**Pull request by acoburn**
See: https://jira.duraspace.org/browse/FCREPO-1657

### CODE REVIEW

**Comment by ajs6f** [comment]
Is this going to prevent Travis from running Javadocs?

**Comment by acoburn** [comment]
@ajs6f my understanding is that travis will continue to run javadocs. If you look at the [travis output](https://s3.amazonaws.com/archive.travis-ci.org/jobs/72877788/log.txt), you will see that it first runs:

    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

(which just downloads dependencies). After that it runs:

    mvn install -B -V

And if you look in the `fcrepo-kernel-api` section, you will see some javadoc warnings, suggesting to me that it is most certainly running `javadoc:jar`

**Comment by ajs6f** [comment]
Oky, but is `javadoc:jar` enough, or do we need `javadoc:test-aggregate` too?

**Comment by acoburn** [comment]
That I don't actually know. I can see where javadoc:jar is being executed: https://github.com/fcrepo4/fcrepo4/blob/master/pom.xml#L1032-L1044

But in the report section: https://github.com/fcrepo4/fcrepo4/blob/master/pom.xml#L1054-L1060 I don't see anything about test-aggregate.

If that is, indeed, the case, that command (`mvn javadoc:test-aggregate`) should not be dropped from the travis.yml file

**Comment by ajs6f** [comment]
Hm. Anyone know who added it or why? @awoods ?

**Comment by awoods** [comment]
`javadoc:test-aggregate` gets run by either the `release:prepare` or site generation steps of the release process. We want to know if there are issues with `javadoc:test-aggregate` prior to pushing the release button.
The `javadoc:test-jar` goal performs the same function:
https://github.com/fcrepo4/fcrepo4/blob/master/pom.xml#L1040

Therefore, it should be safe to remove `javadoc:test-aggregate` from travis.

**Pull request merged**
