### PR TITLE
Tear fcrepo-transform out

### PR DESCRIPTION
**Pull request by whikloj**
Addresses [FCREPO-1670](https://jira.duraspace.org/browse/FCREPO-1670)
- See also https://github.com/whikloj/fcrepo-transform

### CODE REVIEW

**Comment by awoods** [comment]
I assume we will want to make sure the vagrant machinery (fcrepo-webapp-plus) is still including fcrepo-transform so Solr indexing will still work.
That implies moving fcrepo-transform into fcrepo4-exts.

**Comment by whikloj** [comment]
Ok. Since I can't create a repo under fcrepo4-exts. I made the fcrepo-transform under my user. 

Which you can fork or whatever. Is that what you are referring to or did I miss the point?

**Comment by acoburn** [comment]
Here you go: https://github.com/fcrepo4-exts/fcrepo-transform

**Comment by acoburn** [comment]
You'll want to be sure the version history persists.

**Comment by awoods** [comment]
@acoburn, indeed. It looks like the git history got lost during the extraction from the core codebase.

**Comment by acoburn** [comment]
This might be helpful: http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

**Comment by whikloj** [comment]
Still don't think I can push to that repository, but I have fixed mine to maintain the version history.

**Comment by acoburn** [comment]
@whikloj you should be able to issue a PR to that repo

**Comment by whikloj** [comment]
@acoburn I think I would have to clone your empty repo and then fill it again. I think it would be easier if you forked my fcrepo-transform repo into fcrepo-exts.

**Comment by whikloj** [comment]
alternatively, the instructions you gave me worked great if you want to fill the new empty repo in fcrepo4-exts/fcrepo-transform yourself.

**Comment by whikloj** [comment]
@acoburn - or more precisely.
```
git clone https://github.com/fcrepo4/fcrepo4 fcrepo4-transform
git remote rm origin
git filter-branch --subdirectory-filter <directory 1> -- --all
git add remote origin https://github.com/fcrepo4-exts/fcrepo-transform
git branch --set-upstream-to=origin
```

**Comment by awoods** [comment]
The following files also need to be removed (and the entire fcrepo-transform directory):
- https://github.com/whikloj/fcrepo4/blob/3002ad1729122306e630a9ee7c2c77cb1d0384f2/fcrepo-transform/src/main/java/org/fcrepo/transform/TransformationFactory.java
- https://github.com/whikloj/fcrepo4/blob/3002ad1729122306e630a9ee7c2c77cb1d0384f2/fcrepo-transform/src/test/java/org/fcrepo/transform/http/FedoraTransformTest.java

Also, we do not want any dependencies in fcrepo4 on projects in fcrepo4-exts. Therefore, you also need to remove `fcrepo-transform` from the following:
- https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-webapp/pom.xml#L74
- https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-boms/fcrepo4-bom/pom.xml#L91

**Comment by acoburn** [comment]
Also, will fcrepo-transform remain in the org.fcrepo maven group? Or will it change to org.fcrepo.transform?

**Comment by awoods** [comment]
@acoburn, yes, moving to the `org.fcrepo.transform` group makes sense.

**Comment by whikloj** [comment]
so does the parent become the org.sonatype.oss like fcrepo-camel and fcrepo4?

**Comment by acoburn** [comment]
@whikloj I'd keep the parent as it is for now.

**Comment by acoburn** [comment]
@whikloj just an FYI, there is a ticket for creating an `fcrepo-parent` POM so that extension modules can inherit from that rather than from `org.sonatype.oss` (as is currently the case with fcrepo-camel and fcrepo-camel-toolbox): https://jira.duraspace.org/browse/FCREPO-1684

But I have to address some code review comments before we can finalize that ticket.

**Comment by acoburn** [comment]
@whikloj can you rebase this PR with the latest updates from master?

**Comment by whikloj** [comment]
@acoburn rebased

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4/fcrepo4/commit/266bc0ab7f3bec42723f431adee4669b0b163e80

**Pull request closed without merging**
