### PR TITLE
Add remaining SMTs

### PR DESCRIPTION
**Pull request by whikloj**
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3269

# What does this Pull Request do?
Adds in some remaining server managed triples for Binaries (and actually for Containers too).

# How should this be tested?

1. Create a binary
     ```
     curl -i -ufedoraAdmin:fedoraAdmin -H"Content-type: text/plain" -d"Some example text" -XPOST -H"Slug: binary" http://localhost:8080/rest
     ```
1. Get the NonRdfSourceDescription
     ```
     curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/binary
     ```
1.  Before this PR see:
     ```
     <http://localhost:8081/rest/binary>
         fedora:created "2020-04-01T20:50:09.916295Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
         fedora:lastModified "2020-04-01T20:50:09.916295Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
         rdf:type ldp:NonRDFSource ;
         fedora:hasFixityService <http://localhost:8081/rest/binary/fcr:fixity> .
     ```
1. After this PR see:
    ```
     <http://localhost:8081/rest/binary>
        fedora:created           "2020-09-08T20:29:39.273341Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified      "2020-09-08T20:29:39.273341Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:createdBy         "fedoraAdmin" ;
        fedora:lastModifiedBy    "fedoraAdmin" ;
        rdf:type                 ldp:NonRDFSource ;
        rdf:type                 ldp:Resource ;
        rdf:type                 fedora:Resource ;
        rdf:type                 fedora:Binary ;
        premis:hasSize           "17"^^<http://www.w3.org/2001/XMLSchema#long> ;
        ebucore:hasMimeType      "text/plain" ;
        premis:hasMessageDigest  <urn:sha-512:2b416c46c884b38418d91151719a3af1f04cbb5686bc84b4057b3f99124d1920febe43bac16b8a734a13969270a9411186ff5e4ad20af60a8a11d412f96df8c2> ;
        fedora:hasFixityService  <http://localhost:8081/rest/binary/fcr:fixity> .
     ```
# Interested parties
@fcrepo4/committers

### CODE REVIEW

**Comment by awoods** [comment]
Would it be possible to add an integration test along the lines of the description in this PR?

**Comment by awoods** [comment]
Step (2) in the description should likely be:
```
curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/binary/fcr:metadata
```

**Review by awoods — CHANGES_REQUESTED** [review]
Besides the request to add an integration test, this looks good.

**Comment by pwinckles** [comment]
I have not reviewed the code. I just compared the sample output with what I'm working with in the migration code. What about `ebucore:filename`?

**Comment by whikloj** [comment]
@pwinckles good point, I'm not sure where we get that value from or how to set it during creation. If someone could help me then I will add it but displaying an empty filename seems less than helpful.

**Comment by pwinckles** [comment]
> 
> 
> @pwinckles good point, I'm not sure where we get that value from or how to set it during creation. If someone could help me then I will add it but displaying an empty filename seems less than helpful.

You should be able to get it from the resource headers -- `getFilename()`

**Comment by whikloj** [comment]
@awoods I can add a test to `FedoraLdpIT` to test all the triples except CREATED_BY and LAST_MODIFIED_BY as I don't add them when they are `null`. This can only be tested in the WebAC module when authentication is used (I think). Would you like me to recreate the test there to check these two values?

**Comment by whikloj** [comment]
@pwinckles sorry I meant how do I set the "filename" value? So I can test I am doing it right.

**Comment by pwinckles** [comment]
> 
> 
> @pwinckles sorry I meant how do I set the "filename" value? So I can test I am doing it right.

Ah. I'm not sure. Never set it myself. I suspect that it's `Content-Disposition: attachment; filename="filename.jpg"`

**Comment by awoods** [comment]
> @awoods I can add a test to `FedoraLdpIT` to test all the triples except CREATED_BY and LAST_MODIFIED_BY as I don't add them when they are `null`. This can only be tested in the WebAC module when authentication is used (I think). Would you like me to recreate the test there to check these two values?

@whikloj : A test in FedoraLdpIT should be sufficient. Thanks.

**Comment by awoods** [comment]
curl -i -XPUT -H"Content-type: text/plain" --data-binary @file.txt -H"Digest: md5=0f8c6e662d538b85a69fdb775821ebc4, sha=4e142fd51b430f344e7d54ce6abf692e444c9f7f" localhost:8080/rest/file -H"content-disposition: attachment; filename=\"my-favorite-file.txt\""

**Review by awoods — APPROVED** [review]

**Pull request merged**
