### PR TITLE
Catch empty body PUT request error

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://jira.duraspace.org/browse/FCREPO-1667

### CODE REVIEW

**Comment by acoburn** [comment]
@awoods can you rebase this PR against `fcrepo4/master`?

**Comment by awoods** [comment]
@acoburn, rebased.

**Comment by ajs6f** [comment]
Travis appears to have failed. Also, are we confident that all places that Jena might throw a `RuntimeIOException` are places from which we want to map as done here?

**Comment by awoods** [comment]
Alternatives to mapping the Jena `RuntimeIOException` are to:
- inspect the `cause` of the `RuntimeIOException` looking for `JsonParseException`, or
- specifically wrap this statement: https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java#L581

However, the Jena exception seems likely to be the result of a `BAD_REQUEST` scenario.
Regarding Travis, the branch builds locally. Probably a sporadic test error.

**Comment by ajs6f** [comment]
I'd rather take wrap the statement _and_ check for the cause. `RuntimeIOException` is really generic. We could easily catch it and throw something more meaningful.

**Comment by awoods** [comment]
Sure. The downside, of course, is that there may be other places in the code that would benefit from a Jena `RuntimeIOExceptionMapper`.

**Comment by ajs6f** [comment]
Can we be sure what to produce (HTTP) for the generic case?

**Comment by awoods** [comment]
Can you clarify that question?

**Comment by ajs6f** [comment]
It's the same

**Comment by awoods** [comment]
I would answer that question with, "yes", since this particular scenario is the first time the `RuntimeIOException` has surfaced. 

However, if you would feel more comfortable with: 
- wrapping the specific location in `ContentExposingResource`, followed by 
- inspecting the `RuntimeIOException` cause, followed by 
- throwing a Fedora-specific exception (`MalformedRdfException` ??) that is caught by its own exception-mapper, I would be happy to add a new commit.

**Comment by ajs6f** [comment]
I honestly would. The semantics of `RuntimeIOException` are just what you'd think (just an unchecked `IOException`). I think rethrowing something (sure, `MalformedRdfException`, when that's appropriate) inside our code is cleaner. Especially if it turns out that there are several ways for the problem to happen (besides a purely empty body) and we want to distinguish them.

**Comment by awoods** [comment]
New commit responds to comments.
@ajs6f, let me know if this looks good to you. If so, I will squash the two commits.

**Comment by ajs6f** [comment]
Yeah, I like that much better. Thanks!

**Pull request merged**
