### PR TITLE
Update HTTP Headers in response

### PR DESCRIPTION
**Pull request by acoburn**
Addresses: https://jira.duraspace.org/browse/FCREPO-1882

### CODE REVIEW

**Comment by ajs6f** [comment]
👍

**Comment by whikloj** [comment]
This works as expected and I can merge it if everyone is happy. 

I'll mention that I think someone may have added the Vary and Prefer header as part of a previous effort, 'cause when I put a RDFSource and then GET it. There appears the new `Vary: Accept, Prefer` and then an alternate `Vary: Prefer` and `Vary: Accept, Range, Accept-Encoding, Accept-Language`

```
HTTP/1.1 200 OK
Date: Wed, 28 Sep 2016 15:22:02 GMT
ETag: W/"5b72f49a653147ca2508978abd84589ceb8862d8"
Last-Modified: Wed, 28 Sep 2016 15:21:50 GMT
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
Link: <http://www.w3.org/ns/ldp#Container>;rel="type"
Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"
Accept-Patch: application/sparql-update
Accept-Post: text/turtle,text/rdf+n3,text/n3,application/rdf+xml,application/n-triples,application/ld+json,multipart/form-data,application/sparql-update
Vary: Prefer,Accept
Allow: MOVE,COPY,DELETE,POST,HEAD,GET,PUT,PATCH,OPTIONS
Preference-Applied: return=representation
Vary: Prefer
Vary: Accept, Range, Accept-Encoding, Accept-Language
Content-Type: text/turtle
Content-Length: 1908
Server: Jetty(9.3.1.v20150714)
```

I don't think this is a problem, just making note.

**Comment by acoburn** [comment]
@whikloj if the Vary header(s) already contain Prefer and Accept, then they are unneeded to be included here. I will amend the PR

**Comment by whikloj** [comment]
👍

**Pull request merged**
