### PR TITLE
clean up README files

### PR DESCRIPTION
**Pull request by acoburn**
The README is a bit confusing and could be improved greatly. This is a stab at that. This also removes the README file sitting in fcrepo-kernel-modeshape, which seems out of place and confusing.

### CODE REVIEW

**Comment by ajs6f** [comment]
@acoburn ++

Do you want to add something about the "one-click" run?

**Comment by acoburn** [comment]
@ajs6f good thought, I added mention of the one-click application

**Comment by acoburn** [comment]
See: https://jira.duraspace.org/browse/FCREPO-1804

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4/fcrepo4/commit/be7beb8b3d2ef055232afbf8784f41261b4a5843

**Pull request closed without merging**
