### PR TITLE
FCREPO-1868: remove dependency on javax.jcr.Session in kernel-api

### PR DESCRIPTION
**Pull request by ajs6f**

### CODE REVIEW

**Comment by ajs6f** [comment]
Removing `Session` from the API means that it is now appearing explicitly with much greater frequency in the HTTP layers, for now. I think that's unavoidable for the moment. Removing it from the HTTP layers is a whole separate task because of the mistake we made in tightly coupling `Session` with HTTP requests.

**Comment by acoburn** [comment]
Parameterizing the `fcrepo-kernel-api` interfaces makes a lot of sense to me, but pushing the `Session` type into the HTTP layers just shifts the problem. I would expect that the better solution would have `Session` types isolated in the `fcrepo-kernel-modeshape` module.

**Comment by ajs6f** [comment]
It definitely would, and I don't much care. The object here for me is to get this stuff out of the kernel APi so that reimplementation is no longer blocked. The other work of cleaning the HTTP layer can go on later. (And by someone else.)

Eventually, that type parameter must be replaced by an actual Fedora construction. Probably `Transaction`.

**Comment by acoburn** [comment]
Is there anything preventing one from simply using `org.fcrepo.kernel.api.Transaction` as a concrete parameterized type in those cases? In this PR, `Transaction<T>` can already parameterized with a `Session` type.

**Comment by ajs6f** [comment]
No, `Transaction` isn't ready for that. It doesn't actually offer the ability to do anything useful with Fedora resources yet. What we're talking about doing is de-generifying `Transaction` as we move the actual functions that alter repository contents from JCR-specific forms in `Session` to Fedora-specific forms in `Transaction`. If that _is_ what we end up doing.

**Comment by ajs6f** [comment]
@acoburn , is this in abeyance because you are on vacation or because you have continuing or fresh objections?

**Comment by acoburn** [comment]
@ajs6f I am still concerned about having `Session` pushed into the http layers, but I recognize your point about this blocking other development. Unless anyone else has objections, I will plan to merge this later today.

**Comment by ajs6f** [comment]
I'm not trying to push you forward. I'm not going to do anything about this in the next few days anyway (Jena stuff) so if you want to step back and make a more concerted plan to eject JCR from the layers above the kernel, we can do that. Put an item on Thursday's meeting.

**Comment by acoburn** [comment]
That sounds good -- I'll add it to the tech meeting agenda

**Comment by acoburn** [comment]
@ajs6f since the effort that is part of #1107 supersedes this PR, shall we close this one?

**Comment by ajs6f** [comment]
Yeah, I'm fine with that.

**Pull request closed without merging**
