### PR TITLE
Read PATCH requests as UTF-8 encoded input streams

### PR DESCRIPTION
**Pull request by acoburn**
Resolves: https://jira.duraspace.org/browse/FCREPO-1993

### CODE REVIEW

**Comment by whikloj** [comment]
So I am guessing you need to be on a system with a default encoding scheme that is **NOT** UTF-8 to be able to test this properly, yes?

**Comment by ajs6f** [comment]
Theoretically, [no](https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding), but it could make for some messiness in Maven Surefire and Failsafe. Still, we might want to do it.

**Comment by awoods** [comment]
This looks good to me, especially given the integration test and error handling provided by the related 
tickets:
https://jira.duraspace.org/browse/FCREPO-1973
https://jira.duraspace.org/browse/FCREPO-1979

**Comment by whikloj** [comment]
So we are leaving this as being tested manually by Windows users? I don't have a particular problem with that, just wondering.

**Comment by acoburn** [comment]
Anyone can test this by starting the JVM with the file.encoding property set to something other than utf-8. Using a Mac, without the file.encoding value set, this fixes PATCH requests containing utf-8 characters.

**Comment by awoods** [comment]
Given the other testing context around this PR, I am happy to see this move through as-is.

**Pull request merged**
