### PR TITLE
Return the Fedora version number in the Server header

### PR DESCRIPTION
**Pull request by acoburn**
Resolves: https://jira.duraspace.org/browse/FCREPO-1774

### CODE REVIEW

**Comment by ajs6f** [comment]
This looks okay to me but Travis is failing?

**Comment by escowles** [comment]
I spun this up locally, and the tests all passed, but I didn't see the updated Server header in either Tomcat or using `mvn jetty:run`.

**Comment by acoburn** [comment]
@escowles I also saw that when using jetty:run the server header is overwritten by jetty. In a full jetty environment, however, I saw the server header come through (provided that the request was for /rest/*). It also worked for me with a Tomcat 7 deployment -- which version of tomcat were you using?

**Comment by escowles** [comment]
I was using Tomcat 8.0.30 — I just downloaded 7.0.72 and I see the FedoraCommons Server header with that version.  I downloaded the most recent (8.0.38), and it continues to send `Coyote/1.1`.

The [docs](https://tomcat.apache.org/tomcat-8.0-doc/config/http.html#Common_Attributes) say that it should use the header set by the application, but it can be overridden by setting a `server` attribute on the Connector.  I was able to do that, though it would obviously be better if the application can set it.

**Comment by acoburn** [comment]
Honestly, I have no idea why the tests fail on Travis. I have been entirely unable to get the tests to fail on my local machine (despite repeated attempts -- like ~25). Do they fail for everyone else?

I was a little reluctant to push the `@Context HttpServletResponse` into the `FedoraBaseResource` -- I'm assuming that's the cause of the error. It is also possible to implement this with the `@Context HttpServletResponse` left in the `ContentExposingResouce` class -- it will require more code and (arguably) more code duplication, but if these tests keep failing, that may be the only way to approach this.

**Comment by mikedurbin** [comment]
I get errors, but only when I run all the integration tests in fcrepo-http-api.  (2 out of 2 times they appeared when running all the tests, they didn't show up when I ran the failing tests in isolation).  I'll get back to you when I know the cause...

**Comment by awoods** [comment]
The build fails for me in apparently the same fashion as Travis.

**Comment by acoburn** [comment]
@awoods: it would be helpful if you could run the `fcrepo-http-api` integration tests with DEBUG mode turned on (and put the results in a gist).

**Comment by mikedurbin** [comment]
@acoburn, here's a snippet... it's hard to tell if I included too much... but it includes the information about a 500 response to testInvalidVersionReversion...
https://gist.github.com/mikedurbin/172650d3427de5b8a07bd04ab42d8992

**Comment by acoburn** [comment]
@mikedurbin thanks! I can definitely work with that.

**Comment by acoburn** [comment]
I was never able to reproduce the error that everyone else seemed to get (I tried two flavors of linux and OS X), but with some minor refactoring of the `FedoraVersions` class, this now passes the travis test. It seems that the error had something to do with the `PostConstruct` annotation on the `FedoraVersions` class.

**Comment by whikloj** [comment]
Maybe I am doing something wrong, but I also can't see the new Server header in Tomcat. 
```
vagrant@fedora4:/var/lib/tomcat7/webapps$ curl -i -G http://localhost:8080/fcrepo/rest/test
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
ETag: W/"b426caaaf6690672270453bcbb14cd63ec62c659"
Last-Modified: Fri, 04 Nov 2016 21:16:37 GMT
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
Link: <http://www.w3.org/ns/ldp#Container>;rel="type"
Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"
Accept-Patch: application/sparql-update
Accept-Post: text/turtle,text/rdf+n3,text/n3,application/rdf+xml,application/n-triples,application/ld+json,multipart/form-data,application/sparql-update
Allow: MOVE,COPY,DELETE,POST,HEAD,GET,PUT,PATCH,OPTIONS
Preference-Applied: return=representation
Vary: Prefer
Vary: Accept, Range, Accept-Encoding, Accept-Language
Content-Type: text/turtle
Transfer-Encoding: chunked
Date: Tue, 08 Nov 2016 14:43:37 GMT

```

**Comment by acoburn** [comment]
I am going to close this PR. If someone else wants to revive it at some point, they can feel free.

**Pull request closed without merging**
