### PR TITLE
Account for blank nodes in HTML UI

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://jira.duraspace.org/browse/FCREPO-1496

### CODE REVIEW

**Comment by ajs6f** [comment]
Perhaps we can have an IT to prevent regression?

**Comment by awoods** [comment]
I would agree if we had an HTML integration test framework that worked.

**Comment by ajs6f** [comment]
The problem was that an exception was being thrown. We don't need to check the actual HTML, just make a request and get a 200.

**Comment by acoburn** [comment]
@ajs6f are you suggesting that we should wait on merging this until an integration test is written?

**Comment by ajs6f** [comment]
I would.

**Comment by acoburn** [comment]
ok, I'll try to fit this in today.

**Comment by ajs6f** [comment]
Thanks. I think it's worth doing because otherwise, we risk regression as the general bnode problem continues to evolve. We obviously have no test for this now.

**Comment by awoods** [comment]
@acoburn, let me know once you start to work on this integration test... and I will do the same if I start to work on it.

**Comment by acoburn** [comment]
@awoods sounds good

**Comment by acoburn** [comment]
@awoods shall we close this PR? The related ticket is marked as "Closed: Won't Fix"

**Pull request closed without merging**
