### PR TITLE
Adding spans around release info

### PR DESCRIPTION
**Pull request by escowles**
* Adding spans with IDs around release info in HTML UI, to make it easier to parse.

Potential low-impact solution to https://jira.duraspace.org/browse/FCREPO-1774

### CODE REVIEW

**Comment by whikloj** [comment]
You are a whirlwind of productivity 👍

**Comment by ajs6f** [comment]
Would we want to do this with RDFa/DOAP? It's not really semantically correct, but it might be a little clearer down the road. Or maybe I'm being paranoid.

**Comment by whikloj** [comment]
I'd say this is making an unsupported method of determining version number, easier. So we aren't explicitly saying you should do this, but if you want to at least we've made it easier for you. But perhaps I'm not paranoid enough.

**Comment by ajs6f** [comment]
That works for me.

**Comment by ajs6f** [comment]
No one is paranoid enough.

No one.

**Pull request merged**
