### PR TITLE
Splash-page link to registry

### PR DESCRIPTION
**Pull request by yinlinchen**
screen shot 2015-10-02 at 9 47 05 am

Resolves: https://jira.duraspace.org/browse/FCREPO-1593

### CODE REVIEW

**Comment by scossu** [comment]
Would a brief explanation increase visibility? Such as 
>Fedora is maintained by a community of volunteers. Your feedback is important.
>Register your repository at Duraspace to receive updates, etc...

**Comment by ajs6f** [comment]
+1

**Comment by awoods** [comment]
@scossu, your suggested "explanation" text is exactly what @yinlinchen has included. Can you be more specific in what you are suggesting?

**Comment by yinlinchen** [comment]
@awoods I updated the screenshoot after including @scossu's comments.

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4/fcrepo4/commit/a532284d45e53d7dccb2dc17d0c26c738c6b1eb6

**Comment by scossu** [comment]
Actually I did not mean a literal "etc..." but if everybody else is OK with it we may leave it this way.

**Comment by awoods** [comment]
@scossu, actually, I updated the text:
https://github.com/fcrepo4/fcrepo4/commit/a532284d45e53d7dccb2dc17d0c26c738c6b1eb6#diff-0e9f2aa34f2dca9c48998dafe78d700cR32

**Comment by scossu** [comment]
@awoods :+1:

**Pull request closed without merging**
