### PR TITLE
Add warning that the backup and restore endpoints will be externalized

### PR DESCRIPTION
**Pull request by acoburn**
Addresses: https://jira.duraspace.org/browse/FCREPO-2044

### CODE REVIEW

**Comment by awoods** [comment]
Although /fcr:backup and /fcr:restore are not a part of the Fedora Specification, they serve a very real and practical purpose in the community implementation. I would rather we not deprecate them until we have a time-tested alternative in the import-export utility.

**Comment by acoburn** [comment]
@awoods: I think the better approach is to have a command-line utility that _directly_ invokes the methods on [this service](https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/RepositoryServiceImpl.java). Wrapping that service in an HTTP interface makes very little sense to me.

**Comment by acoburn** [comment]
@awoods: or, put another way, once someone starts to develop a non-modeshape implementation (while re-using the existing API classes), are you saying that that implementation _must_ implement a backup and restore endpoint?

**Comment by awoods** [comment]
A command-line tool that interacts with the repository directly has its appeal, but will likely suffer from locking issues with the webapp and the command-line tool trying to access the underlying repository at the same time.

Regarding other implementations of the Fedora API, absolutely not. It seems perfectly reasonable to return a "501 Not Implemented" or another suitable response.

**Comment by ajs6f** [comment]
> Although /fcr:backup and /fcr:restore are not a part of the Fedora Specification, they serve a very real and practical purpose in the community implementation. I would rather we not deprecate them until we have a time-tested alternative in the import-export utility.

Please give specific, concrete, preferably quantifiable conditions that must be reached. Otherwise this is not a real plan, it's just kicking a can down an increasingly narrow alley.

**Comment by acoburn** [comment]
I don't see why we couldn't move the backup/restore functionality into an extension module not unlike how the old `fcrepo-transform` module worked -- i.e. by adding new endpoints to the core API.

**Comment by awoods** [comment]
@acoburn, I was thinking the same thing. Externalizing backup/restore into fcrepo-webapp-plus vs deprecating it makes a lot of sense.

**Comment by ajs6f** [comment]
👍 to moving this to `fcrepo-exts` to begin with. We can move it farther out from there.

**Comment by acoburn** [comment]
@awoods: as for process: should we add a warning header now (i.e. "This endpoint will be moving to an extension module in a future release of Fedora") or simply move the related code into an extension module without any associated warning header? I am inclined to think that a warning header would be appropriate.

**Comment by awoods** [comment]
:+1: to Warning header now.

**Pull request merged**
