### PR TITLE
Add a logger warning when using fcrepo-connector-file

### PR DESCRIPTION
**Pull request by whikloj**
Just until we actually move it.

Related to [FCREPO-2028](https://jira.duraspace.org/browse/FCREPO-2028)

### CODE REVIEW

**Comment by ajs6f** [comment]
Actually, should we mention `fcrepo-webapp-plus` in this or just the Jira ticket?

**Comment by whikloj** [comment]
Not sure, I guess I could just say
*FedoraFileSystemConnector will be removed from the core of Fedora in a coming release. See https://jira.duraspace.org/browse/FCREPO-2028 for more information.*

**Comment by ajs6f** [comment]
That sounds better to me.

**Comment by awoods** [comment]
:+1: on the [wording](https://github.com/fcrepo4/fcrepo4/pull/1065#issuecomment-231183647)

**Pull request merged**
