### PR TITLE
Refuse updates to containers that include If-Match headers

### PR DESCRIPTION
**Pull request by escowles**
Fixes https://jira.duraspace.org/browse/FCREPO-2115

### CODE REVIEW

**Comment by dchandekstark** [comment]
I wonder what @ajs6f meant in https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java#L194-L195 ?

**Comment by ajs6f** [comment]
I think it's fairly clear if you read the whole comment:
```
  * Construct an ETag value from the last modified date and path. JCR has a
     * mix:etag type, but it only takes into account binary properties. We
     * actually want whole-object etag data. TODO : construct and store an ETag
     * value on object modify
```

**Comment by acoburn** [comment]
:-1: see https://github.com/fcrepo4/fcrepo4/pull/1089#issuecomment-238892821 for an explanation.

**Comment by escowles** [comment]
Closed after discussion at https://wiki.duraspace.org/display/FF/2016-08-11+-+Fedora+Tech+Meeting

**Pull request closed without merging**
