### PR TITLE
Add scm and developers to fcrepo-parent pom

### PR DESCRIPTION
**Pull request by awoods**
- Required by release plugin

### CODE REVIEW

**Comment by acoburn** [comment]
Are you sure this belongs in the parent pom and not in the individual project configs? I would encourage you to put this data in the project configs and _not_ in the parent pom.

**Comment by bseeger** [comment]
Hi @acoburn, we're trying to get past this issue where we're failing sonatype validation because that info is not in the parent pom:

`Invalid POM: /org/fcrepo/fcrepo-parent/4.7.1/fcrepo-parent-4.7.1.pom: SCM URL missing, Developer information missing`

**Comment by acoburn** [comment]
what projects are failing? All that data is present in the main fcrepo/pom.xml

**Comment by bseeger** [comment]
Working on fcrepo4 - that fcrepo-parent is the only one failing that POM validation step.

**Comment by acoburn** [comment]
OK, whatever you need to do. But that information isn't in any previous release of `fcrepo-parent`, even if you run `mvn help:effective-pom` on one of those previous releases.

**Comment by awoods** [comment]
I am guessing that each pom needs an SCM section for sonatype/maven-central. The fcrepo-parent/pom.xml used to get that from the sonatype-parent... but we have discontinued using the sonatype parent.

**Comment by acoburn** [comment]
The `<developers>` section is optional and can be omitted. The `scm` section is required. Here's that value from the `fcrepo-parent/4.7.0` release:

```
  <scm>
    <connection>scm:svn:http://svn.sonatype.org/spice/trunk/oss/oss-parenti-9/fcrepo-parent</connection>
    <developerConnection>scm:svn:https://svn.sonatype.org/spice/trunk/oss/oss-parent-9/fcrepo-parent</developerConnection>
    <tag>fcrepo-4.7.0</tag>
    <url>http://svn.sonatype.org/spice/trunk/oss/oss-parent-9/fcrepo-parent</url>
  </scm>
```

which is clearly wrong and which is why we removed the sonatype parent.

**Pull request merged**
