### PR TITLE
Address Sonar major issue - "Final Class"

### PR DESCRIPTION
**Pull request by yinlinchen**
- Checks that class which has only private constructors is declared as final.

Resolves: https://jira.duraspace.org/browse/FCREPO-1322

Note that the Eclipse IDE is automatically format the source code by the defined rule in https://github.com/fcrepo4/fcrepo4/tree/3004d09f7c5bcca041736bfad6e5893e837bc720/src/site/eclipse

mvn checkstyle:check, mvn compile, mvn clean install are all passed.

### CODE REVIEW

**Comment by awoods** [comment]
@yinlinchen, I realize that your IDE reformatted the code and that the reformatted versions also pass the checkstyle checks. However, including unrelated format updates in pull-requests makes it very difficult to inspect git history for functional changes. Please remove the format updates as a new commit on the branch.
@ksclarke, do you have suggestions on how to tame Eclipse?

**Comment by yinlinchen** [comment]
@awoods,  I think the right way is to make the formatted correct. The
Eclipse IDE correctly reformatted the source code and made it right.

Take this PR as an example, the import order in RdfSerializationUtils.java
and CacheEntryFactory.java were wrong and the IDE correct the import order.

As you see the diff, github use dark red/dark green to show the indent, it
is not that difficult for you or other committers to see the formatted
changes.

Unless the source code formatted by intellij and Eclipse (or other IDE) are
different, we should make the source code formatted correct and fix the
wrong format. isn't it?




On Tue, Feb 10, 2015 at 8:32 PM, Andrew Woods <notifications@github.com>
wrote:

> @yinlinchen <https://github.com/yinlinchen>, I realize that your IDE
> reformatted the code and that the reformatted versions also pass the
> checkstyle checks. However, including unrelated format updates in
> pull-requests makes it very difficult to inspect git history for functional
> changes. Please remove the format updates as a new commit on the branch.
> @ksclarke <https://github.com/ksclarke>, do you have suggestions on how
> to tame Eclipse?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fcrepo4/fcrepo4/pull/709#issuecomment-73820499>.
>



-- 
Regards,
Yinlin

**Comment by awoods** [comment]
The issue is with mixing functional and non-functional (formatting) changes in a single commit. 

If you want to reformat classes, you are welcome to. But if you do so, create a separate JIRA ticket for reformatting classes, and make sure that you do not include any functional updates in those commits and make sure that your commit comment clearly states that the updates are non-functional.

**Comment by ajs6f** [comment]
@yinlinchen I have had this conversation with @awoods before, and I think others also have. There's no point in remonstrating with him.

**Comment by yinlinchen** [comment]
Ok, I agree with you.

In Eclipse, there is a function which can reformat source code whole
project/package. So I can very easily to create a JIRA and submit PR about
non-functional (formatting) changes in a couple of minutes.

However, the modified files in this PR will be a lot,  do you or any others
have time to review this PR?

For now, what I can do is to disable the Eclipse save action. Which is
fine, just increasing my time to work on the tickets.

**Comment by awoods** [comment]
@yinlinchen, I agree that reformatting the codebase is likely a waste of everyone's time... because the next person that comes along will want to do it all over again (you are not the first and will not be the last).
A more constructive path is to update the checkstyle rules to be more strict, if you believe there is a specific formatting pattern that should be further enforced.
see: https://github.com/fcrepo4/fcrepo-build-tools/tree/master/src/main/resources/fcrepo-checkstyle

**Comment by ajs6f** [comment]
Checkstyle import directives are listed here:
http://checkstyle.sourceforge.net/config_imports.html

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4/fcrepo4/commit/96993cee1c1ae7bd4c9419e831173c145264f571

**Pull request closed without merging**
