### PR TITLE
Eliminate stacktrace when accessing /fcr:metadata

### PR DESCRIPTION
**Pull request by peichman-umd**
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2867

# What does this Pull Request do?
Eliminate stacktrace when accessing /fcr:metadata

# What's new?
Remove cast to FedoraBinaryImpl since getEffectiveAcl already handles detecting binary nodes gracefully.

# How should this be tested?
Follow the instructions in the original ticket. Observe that when doing a GET or HEAD request to the /fcr:metadata resource, there is a 200 OK response and no stacktrace.

# Interested parties
@whikloj , @fcrepo4/committers

### CODE REVIEW

**Comment by whikloj** [comment]
My API test is still failing, now because of POST to `/fcr:metadata` with the same permissions setup (ie. acl:Append but not acl:Write)
```
> curl -I -utestuser:testpass http://localhost:8080/rest/testsuitecontainer09182018153343/95b75a87-e219-446a-bfa4-b497789a10a7/fcr:metadata -XPOST
HTTP/1.1 500 Server Error
Date: Wed, 19 Sep 2018 21:25:09 GMT
Set-Cookie: JSESSIONID=lxef6epn4rvj1cdeydootuihq;Path=/
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Tue, 18-Sep-2018 21:25:09 GMT
Content-Type: text/html;charset=iso-8859-1
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 13626
Connection: close
Server: Jetty(9.3.1.v20150714)
```

Stacktrace is
```
javax.servlet.ServletException: Filtered request failed.
    at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal (AbstractShiroFilter.java:384)
    at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter (OncePerRequestFilter.java:125)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate (DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter (DelegatingFilterProxy.java:262)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1667)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:581)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:513)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1113)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:511)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1047)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:213)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:109)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle (Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:302)
    at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:238)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run (SelectChannelEndPoint.java:57)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun (ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run (ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:572)
    at java.lang.Thread.run (Thread.java:745)
Caused by: org.fcrepo.kernel.api.exception.RepositoryRuntimeException: javax.jcr.RepositoryException: Error converting "fcr:metadata" from String to a Name
    at org.fcrepo.kernel.modeshape.services.NodeServiceImpl.find (NodeServiceImpl.java:81)
    at org.fcrepo.kernel.modeshape.services.NodeServiceImpl.find (NodeServiceImpl.java:47)
    at org.fcrepo.auth.webac.WebACFilter.resource (WebACFilter.java:136)
    at org.fcrepo.auth.webac.WebACFilter.isAuthorized (WebACFilter.java:218)
    at org.fcrepo.auth.webac.WebACFilter.doFilter (WebACFilter.java:98)
    at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter (ProxiedFilterChain.java:66)
    at org.fcrepo.auth.common.AbstractPrincipalProvider.doFilter (AbstractPrincipalProvider.java:84)
    at org.fcrepo.auth.common.HttpHeaderPrincipalProvider.doFilter (HttpHeaderPrincipalProvider.java:38)
    at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter (ProxiedFilterChain.java:66)
    at org.fcrepo.auth.common.ServletContainerAuthFilter.doFilter (ServletContainerAuthFilter.java:89)
    at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter (ProxiedFilterChain.java:66)
    at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain (AbstractShiroFilter.java:449)
    at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call (AbstractShiroFilter.java:365)
    at org.apache.shiro.subject.support.SubjectCallable.doCall (SubjectCallable.java:90)
    at org.apache.shiro.subject.support.SubjectCallable.call (SubjectCallable.java:83)
    at org.apache.shiro.subject.support.DelegatingSubject.execute (DelegatingSubject.java:387)
    at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal (AbstractShiroFilter.java:362)
    at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter (OncePerRequestFilter.java:125)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate (DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter (DelegatingFilterProxy.java:262)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1667)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:581)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:513)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1113)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:511)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1047)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:213)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:109)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle (Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:302)
    at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:238)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run (SelectChannelEndPoint.java:57)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun (ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run (ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:572)
    at java.lang.Thread.run (Thread.java:745)
Caused by: javax.jcr.RepositoryException: Error converting "fcr:metadata" from String to a Name
    at org.modeshape.jcr.JcrSession.absolutePathFor (JcrSession.java:722)
    at org.modeshape.jcr.JcrSession.getNode (JcrSession.java:859)
    at org.modeshape.jcr.JcrSession.getNode (JcrSession.java:852)
    at org.modeshape.jcr.JcrSession.getNode (JcrSession.java:126)
    at org.fcrepo.kernel.modeshape.services.NodeServiceImpl.find (NodeServiceImpl.java:79)
    at org.fcrepo.kernel.modeshape.services.NodeServiceImpl.find (NodeServiceImpl.java:47)
    at org.fcrepo.auth.webac.WebACFilter.resource (WebACFilter.java:136)
    at org.fcrepo.auth.webac.WebACFilter.isAuthorized (WebACFilter.java:218)
    at org.fcrepo.auth.webac.WebACFilter.doFilter (WebACFilter.java:98)
    at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter (ProxiedFilterChain.java:66)
    at org.fcrepo.auth.common.AbstractPrincipalProvider.doFilter (AbstractPrincipalProvider.java:84)
    at org.fcrepo.auth.common.HttpHeaderPrincipalProvider.doFilter (HttpHeaderPrincipalProvider.java:38)
    at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter (ProxiedFilterChain.java:66)
    at org.fcrepo.auth.common.ServletContainerAuthFilter.doFilter (ServletContainerAuthFilter.java:89)
    at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter (ProxiedFilterChain.java:66)
    at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain (AbstractShiroFilter.java:449)
    at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call (AbstractShiroFilter.java:365)
    at org.apache.shiro.subject.support.SubjectCallable.doCall (SubjectCallable.java:90)
    at org.apache.shiro.subject.support.SubjectCallable.call (SubjectCallable.java:83)
    at org.apache.shiro.subject.support.DelegatingSubject.execute (DelegatingSubject.java:387)
    at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal (AbstractShiroFilter.java:362)
    at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter (OncePerRequestFilter.java:125)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate (DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter (DelegatingFilterProxy.java:262)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1667)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:581)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:513)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1113)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:511)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1047)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:213)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:109)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle (Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:302)
    at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:238)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run (SelectChannelEndPoint.java:57)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun (ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run (ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:572)
    at java.lang.Thread.run (Thread.java:745)
```

Not sure if this is related. It can be part of this or a new ticket.

**Comment by whikloj** [comment]
Also with `PUT`, however `DELETE` correctly responds 403

**Comment by peichman-umd** [comment]
@whikloj I think the `POST`/`PUT` problem is being caused by the `resource("/.../fcr:metadata")` call where the filter is checking whether the resource is an LDP-NR. The node path in Modeshape is "/.../fedora:description", so I need to translate the path first.

**Comment by peichman-umd** [comment]
@whikloj Updated the code to use a URI to JCR node path converter, so it should no longer give you a stacktrace on POST/PUT to fcr:metadata.

**Comment by peichman-umd** [comment]
@dbernstein There are now integration tests for this (thank you @whikloj!)

**Pull request merged**
