### PR TITLE
Remove bundle export of 'org.modeshape' packages

### PR DESCRIPTION
**Pull request by awoods**
Addresses: https://jira.duraspace.org/browse/FCREPO-1535

### CODE REVIEW

**Comment by acoburn** [comment]
:+1: This builds properly for me!

**Comment by acoburn** [comment]
No, actually, I don't think this is entirely correct. The `fcrepo-kernel-impl` package is still generating a split-package.

**Comment by awoods** [comment]
@acoburn, can you please describe the process by which you determine if the bundle generates a "split-package"?
Also, these `org.modeshape` packages/services should not be used by any other bundle in F4 besides fcrepo-kernel-impl. I would hope an easy fix would be to simply eliminate the export of these packages/services from the fcrepo-kernel-impl bundle in the OSGi context.

**Comment by acoburn** [comment]
@awoods, there are several ways to ascertain this. The easiest is by noting the warning from the build machinery (`maven-bundle-plugin`) along these lines: 

    [WARNING] Bundle org.fcrepo:fcrepo-kernel-impl:bundle:4.2.1-SNAPSHOT : Split package, multiple jars provide the same package:org/modeshape/jcr
    Use Import/Export Package directive -split-package:=(merge-first|merge-last|error|first) to get rid of this warning
    Package found in   [Jar:., Jar:modeshape-jcr]
    Class path         [Jar:., Jar:modeshape-jcr, Jar:modeshape-jcr-api, Jar:jcr, Jar:modeshape-common, Jar:joda-time, Jar:modeshape-schematic, Jar:jgroups, Jar:mapdb, Jar:tika-core, Jar:jbossjta, Jar:fcrepo-kernel, Jar:jena-core, Jar:jena-iri, Jar:xercesImpl, Jar:xml-apis, Jar:jena-arq, Jar:jsonld-java, Jar:jackson-core, Jar:httpclient-cache, Jar:libthrift, Jar:commons-lang3, Jar:commons-csv, Jar:javax.inject, Jar:guava, Jar:slf4j-api, Jar:jcl-over-slf4j, Jar:spring-context, Jar:spring-aop, Jar:aopalliance, Jar:spring-beans, Jar:spring-core, Jar:spring-expression, Jar:fcrepo-metrics, Jar:metrics-core, Jar:metrics-graphite, Jar:metrics-jersey2, Jar:metrics-servlets, Jar:metrics-healthchecks, Jar:metrics-json, Jar:metrics-jvm, Jar:jackson-databind, Jar:jackson-annotations, Jar:jena-tdb, Jar:commons-lang, Jar:fcrepo-mint, Jar:httpclient, Jar:httpcore, Jar:commons-codec, Jar:metrics-annotation, Jar:commons-io, Jar:infinispan-core, Jar:jboss-transaction-api_1.1_spec, Jar:jboss-marshalling-river, Jar:jboss-marshalling, Jar:jboss-logging, Jar:infinispan-commons]
    [WARNING] Bundle org.fcrepo:fcrepo-kernel-impl:bundle:4.2.1-SNAPSHOT : Split package, multiple jars provide the same package:org/modeshape/jcr/value/binary/infinispan
    Use Import/Export Package directive -split-package:=(merge-first|merge-last|error|first) to get rid of this warning
    Package found in   [Jar:., Jar:modeshape-jcr]
    Class path         [Jar:., Jar:modeshape-jcr, Jar:modeshape-jcr-api, Jar:jcr, Jar:modeshape-common, Jar:joda-time, Jar:modeshape-schematic, Jar:jgroups, Jar:mapdb, Jar:tika-core, Jar:jbossjta, Jar:fcrepo-kernel, Jar:jena-core, Jar:jena-iri, Jar:xercesImpl, Jar:xml-apis, Jar:jena-arq, Jar:jsonld-java, Jar:jackson-core, Jar:httpclient-cache, Jar:libthrift, Jar:commons-lang3, Jar:commons-csv, Jar:javax.inject, Jar:guava, Jar:slf4j-api, Jar:jcl-over-slf4j, Jar:spring-context, Jar:spring-aop, Jar:aopalliance, Jar:spring-beans, Jar:spring-core, Jar:spring-expression, Jar:fcrepo-metrics, Jar:metrics-core, Jar:metrics-graphite, Jar:metrics-jersey2, Jar:metrics-servlets, Jar:metrics-healthchecks, Jar:metrics-json, Jar:metrics-jvm, Jar:jackson-databind, Jar:jackson-annotations, Jar:jena-tdb, Jar:commons-lang, Jar:fcrepo-mint, Jar:httpclient, Jar:httpcore, Jar:commons-codec, Jar:metrics-annotation, Jar:commons-io, Jar:infinispan-core, Jar:jboss-transaction-api_1.1_spec, Jar:jboss-marshalling-river, Jar:jboss-marshalling, Jar:jboss-logging, Jar:infinispan-commons]
    [WARNING] Bundle org.fcrepo:fcrepo-kernel-impl:bundle:4.2.1-SNAPSHOT : Export org.fcrepo.kernel.impl.services.functions,  has 1,  private references [org.modeshape.jcr.value.binary.infinispan], 
    [WARNING] Bundle org.fcrepo:fcrepo-kernel-impl:bundle:4.2.1-SNAPSHOT : Export org.fcrepo.kernel.impl.spring,  has 1,  private references [org.modeshape.jcr], 
    [WARNING] Bundle org.fcrepo:fcrepo-kernel-impl:bundle:4.2.1-SNAPSHOT : Export org.fcrepo.kernel.impl.utils.impl,  has 1,  private references [org.modeshape.jcr.value.binary.infinispan], 

Next, you can manually inspect the jar:

    $ jar -tvf target/fcrepo-kernel-impl-4.2.1-SNAPSHOT.jar

and see which classes it exports

And finally, you can install the bundle in karaf (drop it in `$KARAF_HOME/deploy`) and then list the classes that are exported

    $ bundle:list
    $ bundle:classes <bundle id>

(the exported classes are in bold)

**Comment by acoburn** [comment]
awoods I issued a PR against your branch that should address this issue. The code still breaks through the modeshape package layer, but there is no longer a split package.

**Comment by acoburn** [comment]
Resolved via 7fefb02fb2db2038bbcf81f2c1744de57c5a7a9b

**Pull request closed without merging**
