### PR TITLE
Updates versions for httpcomponent dependencies (httpclient, httpmime…

### PR DESCRIPTION
**Pull request by bbranan**
…, httpcore) to the most current. This is required for S3 binary store plugin.

### CODE REVIEW

**Comment by ajs6f** [comment]
Does this cause any deprecation warnings?

**Comment by awoods** [comment]
I get the same error as Travis when building locally.
https://travis-ci.org/fcrepo4/fcrepo4/builds/135131767

I would suggest running `mvn clean install` at the top of the codebase to ensure that the PR builds.

**Comment by bbranan** [comment]
@ajs6f: I see no additional deprecation warnings generated by this change.

**Comment by ajs6f** [comment]
Cool.

**Comment by ajs6f** [comment]
@bbranan , please open and "Ready for Test" a ticket for this, and I will merge it.

**Comment by bbranan** [comment]
@ajs6f: Here is the ticket: https://jira.duraspace.org/browse/FCREPO-2049. I don't appear to have the permissions necessary to transition it out of the "Received" state, however.

**Comment by ajs6f** [comment]
Already taken care of by @acoburn!

**Pull request merged**
