### PR TITLE
Update HTML UI logic to support single-subject Binary resources

### PR DESCRIPTION
**Pull request by awoods**
Related to: https://jira.duraspace.org/browse/FCREPO-1640

### CODE REVIEW

**Comment by acoburn** [comment]
I can't claim any significant experience with velocity templates, but I can confirm that the extra triples on binary resources aren't displayed in the HTML view after this patch is applied. However, I still see a "Other Resources" label at the bottom of the page, which is confusing. When I add a binary through the web interface, it creates a new resource with a `fedora:primaryType` equal to `nt:resource`, so the template file used is, therefore, `nt-resource.vsl`, but it appears that this PR is about updating the `nt-file.vsl` template. Shouldn't `nt-resource.vsl` also be updated?

Also, when I add a second version, as described in the ticket (update via `curl -X POST ...`), the template for the old version is, seemingly, all wrong. At least, it doesn't show any values in the main section of the page -- only in the collapsible "Other Resources" section. That node has a `fedora:primaryType = nt:frozenNode`, but there are is no `nt-frozenNode.vsl` template file. Does it then default to `node.vsl`? Either way (in the `fcr:versions/node/fcr:metadata` view), I see triples whose subject is not the resource being described. That is, there are no triples for `</node/fcr:versions/abcdefg>` (other than `fedora:hasFixityService`), but there are plenty of triples for `</node/fcr:versions/abcdefg/fcr:metadata>`

I think this needs more work.

**Comment by awoods** [comment]
@acoburn, the confusion seems to be coming from the fact that you tested [PR-869](https://github.com/fcrepo4/fcrepo4/pull/869) in isolation. PR-869 is not against `master` but instead against the main PR, [PR-864](https://github.com/fcrepo4/fcrepo4/pull/864).
PR-864 makes Fedora single-subject on binaries, whereas PR-869 makes the UI work on top of those underlying updates.
PR-864 has been reviewed, but the UI changes on top has no reviewer... hence the request for your help.
Sorry for the confusion.

**Comment by acoburn** [comment]
@awoods unless I am mistaken, I did test #869 against #864. As for the single-subject issue on binary objects, that is, in fact fixed with this PR. My point, though, may be out of scope for (but not unrelated to) this ticket, namely that the same issue applies to the fcr:version interface, and that I still see a *Other Resources* header at the bottom of the page (with nothing below it) -- not a bug, just a confusing UI element.

**Comment by awoods** [comment]
@ajs6f, I hope you are well and enjoying late summer. When you have a moment, could you please rebase this PR on master?

**Comment by ajs6f** [comment]
Did you not see the question I just asked you in IRC?

**Comment by awoods** [comment]
This PR is now being tracked on https://github.com/fcrepo4/fcrepo4/pull/864

**Pull request closed without merging**
