### PR TITLE
Add integration tests for versioned children

### PR DESCRIPTION
**Pull request by awoods**
Related to: https://jira.duraspace.org/browse/FCREPO-2117

### CODE REVIEW

**Comment by ajs6f** [comment]
I would hold off on this until @acoburn 's PR going to Jena 3 gets through. IIRC, that's the PR in which he removes all this deprecated `GraphStore` stuff.

**Comment by awoods** [comment]
I would also hold off on this until Fedora is updated so that these tests actually pass.

**Comment by awoods** [comment]
I think these are integration tests that verify functionality that will be fixed once https://jira.duraspace.org/browse/FCREPO-2117 is implemented.

**Comment by bseeger** [comment]
This can probably be closed as the versioning model has changed. Any objections to closing this?

**Comment by awoods** [comment]
Close it.

**Pull request closed without merging**
