### PR TITLE
Address copyright date to 2015

### PR DESCRIPTION
**Pull request by yinlinchen**
- change 2014 to 2015 in pom.xml
- run mvn license:format, checkstyle, mvn clean install.
- check the diff

Resolves: https://jira.duraspace.org/browse/FCREPO-1297

### CODE REVIEW

**Comment by awoods** [comment]
I would have expected two updates to the top level pom.xml.

**Comment by yinlinchen** [comment]
updated.

**Comment by awoods** [comment]
I am not seeing a second commit...

**Comment by yinlinchen** [comment]
I use -f again, won't use that anymore.  Can you see my change now?

https://github.com/yinlinchen/fcrepo4/blob/fcrepo-1297/pom.xml

**Pull request merged**
