### PR TITLE
Enables WebAC by default.

### PR DESCRIPTION
**Pull request by dbernstein**
Note:  this commit currently breaks the "clickability" of the one click.
See modifications to the README for new instructions. FWIW I tried a number of different
approaches including ensuring that the the filtered jetty-one-click.xml  ended up in the
jetty console jar as  WEB-INF/jetty.xml.  To no avail.

Resolves  https://jira.duraspace.org/browse/FCREPO-2631

# What's new?
Basically this PR brings over webac the configuration from fcrepo-webapp-plus into the fcrepo-webapp module, ensuring that users who fire up fcrepo-webapp using the mvn jetty:run or the jetty console jar are able to see the webac framework in action.

# How should this be tested?
Fire up the webapp as you normally would.  See README for the jetty console launch command.
You can login using fedoraAdmin:fedoraAdmin as your credentials.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @fcrepo4/committers

### CODE REVIEW

**Comment by dbernstein** [comment]
@awoods :  hold off on testing this until I work out a fix for the integration test failures.

**Comment by dbernstein** [comment]
@awoods :  okay this should be ready to go.  one click is once again one-clicky.  Other issues addressed.  <whew!>

**Comment by dbernstein** [comment]
@awoods :  okay - the auth has been pulled out for the one-click.

**Comment by awoods** [comment]
As of : https://github.com/fcrepo4/fcrepo4/pull/1246/commits/bc108bf7a14dfcf6c5d49061b242480edf91f9b5

When I run:
$mvn clean install -Pone-click
$java -jar fcrepo-webapp/target/fcrepo-webapp-5.0.0-SNAPSHOT-jetty-console.jar --headless

...I get a 403 with:
$curl -i localhost:8080/rest
$curl -i localhost:8080/rest -ufedoraAdmin:fedoraAdmin
$curl -i localhost:8080/rest -ufedoraAdmin:secret3

Should I be doing something differently?

**Comment by dbernstein** [comment]
@awoods:  my bad - I thought it was working, but my browser was caching my credentials.  I will fix.

**Comment by dbernstein** [comment]
or possibly I just looked at "/" rather than "/rest"

**Comment by dbernstein** [comment]
@awoods :  it is fixed now.

**Pull request merged**
