### PR TITLE
Only warn about namespaces mismatches if there are any user-defined namespaces

### PR DESCRIPTION
**Pull request by escowles**
Fixes https://jira.duraspace.org/browse/FCREPO-1920

### CODE REVIEW

**Comment by whikloj** [comment]
:+1:  to not seeing these warnings every time.

**Comment by awoods** [comment]
Is there a ticket associated with this PR?

**Comment by whikloj** [comment]
I couldn't find one, but I can certainly create one if @escowles doesn't mind.

**Comment by escowles** [comment]
@awoods I went ahead and created a ticket and linked between it and this issue: https://jira.duraspace.org/browse/FCREPO-1920

**Comment by awoods** [comment]
Thanks, @escowles.

**Pull request merged**
