### PR TITLE
Reproduce the Same Name Sibling bug with walk around fixing solution.

### PR DESCRIPTION
**Pull request by lsitu**
Related to: https://jira.duraspace.org/browse/FCREPO-2055

### CODE REVIEW

**Comment by ajs6f** [comment]
Does the bug actually appear in this branch?

**Comment by ajs6f** [comment]
👎 to this PR-- we should be following this up with MODE instead, especially after @acoburn 's fix for FCREPO-2080.

**Comment by lsitu** [comment]
Okay. @awoods Is it sufficient to report the SN-Sibling bug with test case above?

**Comment by lsitu** [comment]
I would close the PR now since we all aware that the Same Name Sibling issue is still existing in Modeshape 5.

**Pull request closed without merging**
