### PR TITLE
Address situation when getBaseVersion() must wait for state to persist

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://jira.duraspace.org/browse/FCREPO-2053

### CODE REVIEW

**Comment by awoods** [comment]
Note: Ideally this PR should be verified by @dchandekstark before being merged with `master`.

**Comment by ajs6f** [comment]
Is this still waiting on a response from @dchandekstark?

**Comment by dchandekstark** [comment]
We are no longer experiencing the problem, so I don't have a strong opinion about merging the PR.

**Comment by awoods** [comment]
Closing as "can not reproduce".

**Pull request closed without merging**
