### PR TITLE
Update dependency versions

### PR DESCRIPTION
**Pull request by acoburn**
Addresses: https://jira.duraspace.org/browse/FCREPO-2285
Resolves: https://jira.duraspace.org/browse/FCREPO-2279

### CODE REVIEW

**Comment by awoods** [comment]
:+1:

**Comment by awoods** [comment]
@fcrepo4/committers : :+1: ? :-1: ?

**Comment by escowles** [comment]
👍  — esp. since this includes Modeshape 5.2 with S3 support https://modeshape.wordpress.com/2016/09/28/modeshape-5-2-0-final-is-available/

**Comment by acoburn** [comment]
@escowles sweet! I didn't know that MODE 5.2 had the improved AWS support

**Pull request merged**
